import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import {
  approveArtwork, cancelPackingRun, completePackingRun, createArtwork, createPackingRun, getArtwork,
  getFinishedLot, getPackingRun, listArtworks, listFinishedGoods, listPackingRuns, retireArtwork, updateArtwork,
  type Artwork, type ArtworkWorkspace as ArtworkData, type FinishedGoodsWorkspace as FinishedData,
  type FinishedLot, type PackingRun, type PackingWorkspace as PackingData,
} from '../api/manufacturingExecution';
import { StatusBadge } from './StatusBadge';
import {
  addMonths, applyFailure, date, dateTime, Datum, decimal, Detail, DetailHead, emptyFeedback, Empty,
  Field, FormActions, LineTable, ManufacturingWorkspace, nullable, numeric, today, useManufacturingContextKey,
} from './ManufacturingWorkspaceShell';

export function PackagingArtworkWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<ArtworkData | null>(null); const [selected, setSelected] = useState<Artwork | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(blankArtwork());
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listArtworks({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load packaging artwork.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form, selected?.record_version]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { setSelected(await getArtwork(id)); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load artwork detail.'); } }
  function startNew() { setSelected(null); setForm(blankArtwork()); setEditing(true); setFeedback(emptyFeedback()); }
  function startEdit() { if (!selected) return; setForm({ output_sku_id: selected.output_sku.id, artwork_code: selected.artwork_code, revision: String(selected.revision), label_name: selected.label_name, barcode: selected.barcode, coding_template: selected.coding_template, effective_from: selected.effective_from, effective_to: selected.effective_to ?? '', notes: selected.notes ?? '' }); setEditing(true); setFeedback(emptyFeedback()); }
  function selectSku(id: string) { const sku = workspace?.lookups.output_skus.find((row) => row.id === id); setForm((row) => ({ ...row, output_sku_id: id, barcode: row.barcode || sku?.barcode || '' })); }
  async function save(event: FormEvent) {
    event.preventDefault(); const fields: Record<string, string> = {}; if (!selected && !form.output_sku_id) fields.output_sku_id = 'Choose a finished-good SKU.'; if (!selected && !form.artwork_code.trim()) fields.artwork_code = 'Artwork code is required.'; if (!form.label_name.trim()) fields.label_name = 'Label name is required.'; if (!form.barcode.trim()) fields.barcode = 'Barcode is required.'; if (!form.coding_template.trim()) fields.coding_template = 'Coding template is required.'; if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted artwork fields.', success: null, fields }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); const mutable = { label_name: form.label_name.trim(), barcode: form.barcode.trim(), coding_template: form.coding_template.trim(), effective_from: form.effective_from, effective_to: form.effective_to || null, notes: nullable(form.notes) }; const result = selected ? await updateArtwork(selected, mutable, key.current) : await createArtwork({ ...mutable, output_sku_id: form.output_sku_id, artwork_code: form.artwork_code.trim().toUpperCase(), revision: Number(form.revision) }, key.current); key.current = null; await refresh(); setSelected(await getArtwork(result.id)); setEditing(false); setFeedback({ error: null, success: selected ? 'Draft artwork updated.' : 'Draft artwork revision created.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to save artwork.'); } finally { setBusy(false); }
  }
  async function command(action: 'APPROVE' | 'RETIRE') { if (!selected) return; const reason = action === 'RETIRE' ? window.prompt('Retirement reason') : null; if (action === 'RETIRE' && !reason?.trim()) return; setBusy(true); try { action === 'APPROVE' ? await approveArtwork(selected, crypto.randomUUID()) : await retireArtwork(selected, reason!.trim(), crypto.randomUUID()); await refresh(); setSelected(await getArtwork(selected.id)); setFeedback({ error: null, success: action === 'APPROVE' ? 'Artwork approved for its effective date window.' : 'Artwork retired from future packing runs.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to complete the artwork command.'); } finally { setBusy(false); } }
  return <ManufacturingWorkspace code="PACK-ART" title="Artwork & Coding" description="Version product labels, barcodes, date windows, and batch-code templates before packing." notice="Only one effective approved revision per SKU may be used; completed packing runs retain their artwork snapshot." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CREATE') ? startNew : undefined} headings={['Artwork / revision', 'Finished SKU', 'Label', 'Effective', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.artwork_code}</b><small>revision {row.revision} · v{row.record_version}</small></>, row.output_sku.code, <><b>{row.label_name}</b><small>{row.barcode}</small></>, `${date(row.effective_from)} – ${date(row.effective_to)}`, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Finished SKU<select aria-label="Artwork finished SKU" disabled={!!selected} value={form.output_sku_id} onChange={(e) => selectSku(e.target.value)}><option value="">Select SKU</option>{workspace?.lookups.output_skus.map((sku) => <option key={sku.id} value={sku.id}>{sku.code} · {sku.name}</option>)}</select><Field text={feedback.fields.output_sku_id} /></label><label>Artwork code<input disabled={!!selected} value={form.artwork_code} onChange={(e) => setForm({ ...form, artwork_code: e.target.value })} /><Field text={feedback.fields.artwork_code} /></label><label>Revision<input disabled={!!selected} type="number" min="1" value={form.revision} onChange={(e) => setForm({ ...form, revision: e.target.value })} /></label><label>Label name<input value={form.label_name} onChange={(e) => setForm({ ...form, label_name: e.target.value })} /><Field text={feedback.fields.label_name} /></label><label>Barcode<input value={form.barcode} onChange={(e) => setForm({ ...form, barcode: e.target.value })} /><Field text={feedback.fields.barcode} /></label><label>Effective from<input type="date" value={form.effective_from} onChange={(e) => setForm({ ...form, effective_from: e.target.value })} /></label><label>Effective to<input type="date" value={form.effective_to} onChange={(e) => setForm({ ...form, effective_to: e.target.value })} /></label><label className="wide">Coding template<input aria-label="Coding template" value={form.coding_template} onChange={(e) => setForm({ ...form, coding_template: e.target.value })} /><small>Tokens: {'{LOT} {MFG} {EXP} {BATCH}'}</small><Field text={feedback.fields.coding_template} /></label><label className="wide">Notes<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit={selected ? 'Save artwork' : 'Create artwork revision'} /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Artwork" value={`${selected.artwork_code} revision ${selected.revision}`} /><Datum text="Finished SKU" value={`${selected.output_sku.code} · ${selected.output_sku.name}`} /><Datum text="Label" value={selected.label_name} /><Datum text="Barcode" value={selected.barcode} /><Datum text="Effective" value={`${date(selected.effective_from)} – ${date(selected.effective_to)}`} /><Datum text="Approved" value={dateTime(selected.approved_at)} /><Datum wide text="Coding template" value={<code>{selected.coding_template}</code>} /><Datum wide text="Notes" value={selected.notes ?? 'No notes'} /><Datum wide text="Retirement" value={selected.retirement_reason ?? '—'} /></dl><div className="form-actions">{selected.allowed_actions.includes('UPDATE') ? <button className="secondary" disabled={busy} onClick={startEdit}>Edit draft</button> : null}{selected.allowed_actions.includes('APPROVE') ? <button className="primary" disabled={busy} onClick={() => void command('APPROVE')}>Approve artwork</button> : null}{selected.allowed_actions.includes('RETIRE') ? <button className="secondary" disabled={busy} onClick={() => void command('RETIRE')}>Retire artwork</button> : null}</div></Detail>
      : <Empty text="Choose an artwork revision or create a new controlled label." />}
  </ManufacturingWorkspace>;
}

export function PackingRunWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<PackingData | null>(null); const [selected, setSelected] = useState<PackingRun | null>(null); const [editing, setEditing] = useState(false); const [form, setForm] = useState(blankPacking());
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(emptyFeedback()); const key = useRef<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listPackingRuns({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load packing runs.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setEditing(false); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]); useEffect(() => { key.current = null; }, [form]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { setSelected(await getPackingRun(id)); setEditing(false); } catch (error) { applyFailure(setFeedback, error, 'Unable to load packing-run detail.'); } }
  function startNew() { setSelected(null); setForm(blankPacking()); setEditing(true); setFeedback(emptyFeedback()); }
  function chooseOrder(id: string) { const order = workspace?.lookups.production_orders.find((row) => row.id === id); const art = workspace?.lookups.artworks.find((row) => row.output_sku_id === order?.output_sku?.id); setForm((row) => ({ ...row, production_order_id: id, packaging_artwork_id: art?.id ?? '', packed_quantity: order ? String(Math.max(0, numeric(order.good_quantity) - numeric(order.packed_quantity))) : '' })); }
  async function save(event: FormEvent) {
    event.preventDefault(); const fields: Record<string, string> = {}; if (!form.run_number.trim()) fields.run_number = 'Run number is required.'; if (!form.production_order_id) fields.production_order_id = 'Choose a quality-released batch.'; if (!form.packaging_artwork_id) fields.packaging_artwork_id = 'Choose effective approved artwork.'; if (numeric(form.packed_quantity) <= 0) fields.packed_quantity = 'Enter a positive packed quantity.'; if (!form.finished_lot_code.trim()) fields.finished_lot_code = 'Finished lot code is required.'; if (!form.target_location_id) fields.target_location_id = 'Choose a finished-goods location.'; if (Object.keys(fields).length) { setFeedback({ error: 'Correct the highlighted packing fields.', success: null, fields }); return; }
    setBusy(true); try { key.current ??= crypto.randomUUID(); const result = await createPackingRun({ run_number: form.run_number.trim().toUpperCase(), production_order_id: form.production_order_id, packaging_artwork_id: form.packaging_artwork_id, packed_quantity: form.packed_quantity, finished_lot_code: form.finished_lot_code.trim().toUpperCase(), manufacture_date: form.manufacture_date, expiry_date: form.expiry_date, target_location_id: form.target_location_id, notes: nullable(form.notes) }, key.current); key.current = null; await refresh(); setSelected(await getPackingRun(result.id)); setEditing(false); setFeedback({ error: null, success: 'Draft packing run created with rendered lot coding.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to create the packing run.'); } finally { setBusy(false); }
  }
  async function command(action: 'COMPLETE' | 'CANCEL') { if (!selected) return; const reason = action === 'CANCEL' ? window.prompt('Cancellation reason') : null; if (action === 'CANCEL' && !reason?.trim()) return; setBusy(true); try { action === 'COMPLETE' ? await completePackingRun(selected, crypto.randomUUID()) : await cancelPackingRun(selected, reason!.trim(), crypto.randomUUID()); await refresh(); setSelected(await getPackingRun(selected.id)); setFeedback({ error: null, success: action === 'COMPLETE' ? 'Packing completed; finished stock and lot genealogy posted.' : 'Packing run cancelled.', fields: {} }); } catch (error) { applyFailure(setFeedback, error, 'Unable to complete the packing command.'); } finally { setBusy(false); } }
  const chosenOrder = workspace?.lookups.production_orders.find((row) => row.id === form.production_order_id); const artworks = workspace?.lookups.artworks.filter((row) => !chosenOrder || row.output_sku_id === chosenOrder.output_sku?.id) ?? [];
  return <ManufacturingWorkspace code="PACK-RUN" title="Packing Run" description="Pack quality-released output with effective artwork and receive a traceable finished-goods lot." notice="Completion atomically renders coding, creates the lot, receives stock, and links every issued input lot." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} onNew={workspace?.allowed_actions.includes('CREATE') ? startNew : undefined} headings={['Run / lot', 'Production batch', 'Artwork', 'Quantity', 'Dates', 'Status']} rows={workspace?.data.map((row) => [<><b>{row.run_number}</b><small>{row.finished_lot_code}</small></>, `${row.production_order.number} / ${row.production_order.batch_number}`, `${row.artwork.code} r${row.artwork.revision}`, `${decimal(row.packed_quantity)} ${row.uom_code}`, `${date(row.manufacture_date)} – ${date(row.expiry_date)}`, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {editing ? <form className="requisition-form" onSubmit={save}><fieldset disabled={busy}><div className="requisition-field-grid"><label>Run number<input value={form.run_number} onChange={(e) => setForm({ ...form, run_number: e.target.value })} /><Field text={feedback.fields.run_number} /></label><label>Finished lot code<input value={form.finished_lot_code} onChange={(e) => setForm({ ...form, finished_lot_code: e.target.value })} /><Field text={feedback.fields.finished_lot_code} /></label><label className="wide">Quality-released batch<select aria-label="Quality-released batch" value={form.production_order_id} onChange={(e) => chooseOrder(e.target.value)}><option value="">Select batch</option>{workspace?.lookups.production_orders.map((order) => <option key={order.id} value={order.id}>{order.number} / {order.batch_number} · available {decimal(numeric(order.good_quantity) - numeric(order.packed_quantity))}</option>)}</select><Field text={feedback.fields.production_order_id} /></label><label className="wide">Approved artwork<select aria-label="Approved artwork" value={form.packaging_artwork_id} onChange={(e) => setForm({ ...form, packaging_artwork_id: e.target.value })}><option value="">Select artwork</option>{artworks.map((art) => <option key={art.id} value={art.id}>{art.artwork_code} revision {art.revision} · {art.label_name}</option>)}</select><Field text={feedback.fields.packaging_artwork_id} /></label><label>Packed quantity<input aria-label="Packed quantity" type="number" min="0.000001" step="0.000001" value={form.packed_quantity} onChange={(e) => setForm({ ...form, packed_quantity: e.target.value })} /><Field text={feedback.fields.packed_quantity} /></label><label>Destination<select aria-label="Finished-goods location" value={form.target_location_id} onChange={(e) => setForm({ ...form, target_location_id: e.target.value })}><option value="">Select location</option>{workspace?.lookups.locations.map((location) => <option key={location.id} value={location.id}>{location.code} · {location.name}</option>)}</select><Field text={feedback.fields.target_location_id} /></label><label>Manufacture date<input type="date" value={form.manufacture_date} onChange={(e) => setForm({ ...form, manufacture_date: e.target.value, expiry_date: addMonths(e.target.value, 6) })} /></label><label>Expiry date<input type="date" value={form.expiry_date} onChange={(e) => setForm({ ...form, expiry_date: e.target.value })} /></label><label className="wide">Notes<textarea rows={3} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><FormActions busy={busy} onClose={() => setEditing(false)} submit="Create packing run" /></fieldset></form>
      : selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Run / lot" value={`${selected.run_number} / ${selected.finished_lot_code}`} /><Datum text="Production batch" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Artwork" value={`${selected.artwork.code} r${selected.artwork.revision}`} /><Datum text="Packed quantity" value={`${decimal(selected.packed_quantity)} ${selected.uom_code}`} /><Datum text="Destination" value={selected.target_location.code} /><Datum text="Dates" value={`${date(selected.manufacture_date)} – ${date(selected.expiry_date)}`} /><Datum wide text="Rendered coding" value={<code>{selected.coding_value}</code>} /><Datum text="Completed" value={dateTime(selected.completed_at)} /><Datum wide text="Notes" value={selected.notes ?? 'No notes'} /></dl>{selected.genealogy_edges?.length ? <><h4>Input lot genealogy</h4><LineTable heads={['Input lot', 'Input quantity', 'Output quantity']} rows={selected.genealogy_edges.map((edge) => [edge.input_lot_code, `${decimal(edge.input_quantity)} ${edge.input_uom_code}`, `${decimal(edge.output_quantity)} ${edge.output_uom_code}`])} /></> : null}<div className="form-actions">{selected.allowed_actions.includes('COMPLETE') ? <button className="primary" disabled={busy} onClick={() => void command('COMPLETE')}>Complete and receive stock</button> : null}{selected.allowed_actions.includes('CANCEL') ? <button className="secondary" disabled={busy} onClick={() => void command('CANCEL')}>Cancel run</button> : null}</div></Detail>
      : <Empty text="Choose a packing run or create one from quality-released output." />}
  </ManufacturingWorkspace>;
}

export function FinishedGoodsWorkspace() {
  const contextKey = useManufacturingContextKey(); const [workspace, setWorkspace] = useState<FinishedData | null>(null); const [selected, setSelected] = useState<FinishedLot | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('NEWEST'); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [feedback, setFeedback] = useState(emptyFeedback());
  const refresh = useCallback(async () => { setLoading(true); try { setWorkspace(await listFinishedGoods({ q: search || undefined, status: status || undefined, sort, page })); } catch (error) { applyFailure(setFeedback, error, 'Unable to load finished-goods lots.'); } finally { setLoading(false); } }, [contextKey, search, status, sort, page]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { setSelected(null); setSearch(''); setStatus(''); setPage(1); setFeedback(emptyFeedback()); }, [contextKey]);
  async function choose(id: string) { setFeedback(emptyFeedback()); try { setSelected(await getFinishedLot(id)); } catch (error) { applyFailure(setFeedback, error, 'Unable to load finished-lot detail.'); } }
  return <ManufacturingWorkspace code="FG-LOT" title="Finished Goods" description="Inspect released finished lots, stock balances, batch coding, and upstream material genealogy." notice="Finished lots are created only by completed packing runs and remain linked to their production batch and receipt movement." loading={loading} feedback={feedback} workspace={workspace} search={search} setSearch={setSearch} status={status} setStatus={setStatus} sort={sort} setSort={setSort} page={page} setPage={setPage} headings={['Lot', 'SKU', 'Production batch', 'Location', 'On hand', 'Status']} rows={workspace?.data.map((row) => [row.lot_code, <><b>{row.sku.code}</b><small>{row.sku.name}</small></>, `${row.production_order.number} / ${row.production_order.batch_number}`, row.position.location_code, `${decimal(row.position.quantity)} ${row.position.uom_code}`, <StatusBadge status={row.status} />]) ?? []} ids={workspace?.data.map((row) => row.id) ?? []} selectedId={selected?.id} onOpen={choose}>
    {selected ? <Detail><DetailHead status={selected.status} version={selected.record_version} /><dl className="control-definition"><Datum text="Finished lot" value={selected.lot_code} /><Datum text="SKU" value={`${selected.sku.code} · ${selected.sku.name}`} /><Datum text="Production batch" value={`${selected.production_order.number} / ${selected.production_order.batch_number}`} /><Datum text="Packing run" value={selected.packing_run.number} /><Datum text="Manufactured" value={date(selected.manufacture_date)} /><Datum text="Expiry" value={date(selected.expiry_date)} /><Datum text="Stock" value={`${decimal(selected.position.quantity)} ${selected.position.uom_code}`} /><Datum text="Location" value={`${selected.position.location_code} · ${selected.position.location_name}`} /><Datum text="Quality" value={<StatusBadge status={selected.position.quality_status} />} /><Datum wide text="Batch coding" value={<code>{selected.coding_value}</code>} /></dl><h4>Upstream material lots</h4><LineTable heads={['Input lot', 'Material', 'Consumed']} rows={selected.inputs?.map((input) => [input.lot.code, <><b>{input.lot.item_code}</b><small>{input.lot.item_name}</small></>, `${decimal(input.quantity)} ${input.uom_code}`]) ?? []} /></Detail> : <Empty text="Choose a finished-goods lot to inspect its stock and genealogy." />}
  </ManufacturingWorkspace>;
}

function blankArtwork() { return { output_sku_id: '', artwork_code: '', revision: '1', label_name: '', barcode: '', coding_template: 'LOT {LOT} MFG {MFG} EXP {EXP} BATCH {BATCH}', effective_from: today(), effective_to: '', notes: '' }; }
function blankPacking() { const manufacture = today(); return { run_number: '', production_order_id: '', packaging_artwork_id: '', packed_quantity: '', finished_lot_code: '', manufacture_date: manufacture, expiry_date: addMonths(manufacture, 6), target_location_id: '', notes: '' }; }
