<?php

namespace App\Modules\Finance\Application;

use App\Shared\Audit\AuditService;
use App\Shared\Idempotency\IdempotencyService;
use App\Shared\Outbox\OutboxService;
use Carbon\CarbonImmutable;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpKernel\Exception\ConflictHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

final class FinanceSupplementService
{
    public const ADJUSTMENT_TYPES = ['ACCRUAL', 'RECLASSIFICATION', 'CORRECTION', 'PROVISION'];
    public const DOCUMENT_TYPES = ['SUPPLIER_INVOICE', 'CUSTOMER_INVOICE', 'EXPENSE', 'TAX', 'OTHER'];
    public const SUPPORT_CATEGORIES = ['POSTING', 'RECONCILIATION', 'IMPORT', 'ACCESS', 'OTHER'];
    public const SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

    public function __construct(
        private readonly IdempotencyService $idempotency,
        private readonly AuditService $audit,
        private readonly OutboxService $outbox,
        private readonly FinanceOperationsService $ledger,
    ) {}

    public function createSimulation(array $data): array
    {
        return DB::transaction(function () use ($data): array {
            $namespace = 'finance.simulation.create'; if ($replay = $this->begin($namespace, $data)) return $replay; $this->unique('finance_simulations', 'simulation_number', $data['simulation_number'], $data); [$lines, $debit, $credit] = $this->lines($data['lines'], $data, false); $id = (string) Str::uuid(); $now = CarbonImmutable::now();
            DB::table('finance_simulations')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'simulation_number' => $data['simulation_number'], 'name' => trim($data['name']), 'description' => $this->nullable($data['description'] ?? null), 'as_of_date' => $data['as_of_date'], 'status' => 'DRAFT', 'total_debit' => $debit, 'total_credit' => $credit, 'projected_profit' => 0, 'result_json' => null, 'record_version' => 1, 'created_by' => $data['actor_id'], 'run_at' => null, 'run_by' => null, 'created_at' => $now, 'updated_at' => $now]); $this->insertLines('finance_simulation_lines', 'finance_simulation_id', $id, $lines, $data, $now, true);
            $result = $this->result('finance_simulation', $id, 'DRAFT', 1, ['total_debit' => $debit, 'total_credit' => $credit]); $this->record('CREATE_FINANCE_SIMULATION', 'finance.simulation.created', 'finance_simulation', $id, $data, 1, ['line_count' => count($lines), 'ledger_effect' => 'NONE'], $result); $this->complete($namespace, $data, $result); return $result;
        }, 3);
    }

    public function runSimulation(string $id, array $data): array
    {
        return DB::transaction(function () use ($id, $data): array {
            $namespace = 'finance.simulation.run.'.$id; if ($replay = $this->begin($namespace, $data + ['simulation_id' => $id])) return $replay; $simulation = $this->find('finance_simulations', $id, $data, 'Finance simulation', true); $this->version($simulation, $data, 'finance simulation'); $this->status($simulation, ['DRAFT', 'RUN'], 'Only a draft or previously run simulation can be recalculated.');
            $rows = DB::table('finance_simulation_lines as line')->join('chart_accounts as account', 'account.id', '=', 'line.account_id')->where('line.finance_simulation_id', $id)->get(['line.*', 'account.account_type', 'account.account_code']); $revenue = $expense = '0.0000'; foreach ($rows as $row) { if ($row->account_type === 'REVENUE') $revenue = bcadd($revenue, bcsub($this->decimal($row->credit_amount), $this->decimal($row->debit_amount), 4), 4); if ($row->account_type === 'EXPENSE') $expense = bcadd($expense, bcsub($this->decimal($row->debit_amount), $this->decimal($row->credit_amount), 4), 4); } $profit = bcsub($revenue, $expense, 4); $snapshot = ['ledger_isolated' => true, 'as_of_date' => (string) $simulation->as_of_date, 'revenue' => $revenue, 'expense' => $expense, 'projected_profit' => $profit, 'line_count' => $rows->count(), 'assumptions' => $rows->map(fn (object $row) => ['account_code' => $row->account_code, 'assumption' => $row->assumption])->filter(fn (array $row) => $row['assumption'] !== null)->values()->all()]; $version = (int) $simulation->record_version + 1;
            DB::table('finance_simulations')->where('id', $id)->update(['status' => 'RUN', 'projected_profit' => $profit, 'result_json' => json_encode($snapshot, JSON_THROW_ON_ERROR), 'run_at' => now(), 'run_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $result = $this->result('finance_simulation', $id, 'RUN', $version, ['projected_profit' => $profit, 'result' => $snapshot]); $this->record('RUN_FINANCE_SIMULATION', 'finance.simulation.run', 'finance_simulation', $id, $data, $version, ['ledger_effect' => 'NONE', 'projected_profit' => $profit], $result); $this->complete($namespace, $data, $result); return $result;
        }, 3);
    }

    public function createAdjustment(array $data): array
    {
        return DB::transaction(function () use ($data): array { $namespace = 'finance.adjustment.create'; if ($replay = $this->begin($namespace, $data)) return $replay; $this->unique('finance_adjustments', 'adjustment_number', $data['adjustment_number'], $data); [$lines, $debit, $credit] = $this->lines($data['lines'], $data, true); $id = (string) Str::uuid(); $now = CarbonImmutable::now(); DB::table('finance_adjustments')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'adjustment_number' => $data['adjustment_number'], 'adjustment_date' => $data['adjustment_date'], 'adjustment_type' => $data['adjustment_type'], 'reason' => trim($data['reason']), 'status' => 'DRAFT', 'total_debit' => $debit, 'total_credit' => $credit, 'journal_id' => null, 'record_version' => 1, 'created_by' => $data['actor_id'], 'submitted_at' => null, 'submitted_by' => null, 'approved_at' => null, 'approved_by' => null, 'posted_at' => null, 'posted_by' => null, 'cancelled_at' => null, 'cancelled_by' => null, 'cancellation_reason' => null, 'created_at' => $now, 'updated_at' => $now]); $this->insertLines('finance_adjustment_lines', 'finance_adjustment_id', $id, $lines, $data, $now); $result = $this->result('finance_adjustment', $id, 'DRAFT', 1, ['total_debit' => $debit]); $this->record('CREATE_FINANCE_ADJUSTMENT', 'finance.adjustment.created', 'finance_adjustment', $id, $data, 1, ['line_count' => count($lines)], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function transitionAdjustment(string $id, string $action, ?string $reason, array $data): array
    {
        return DB::transaction(function () use ($id, $action, $reason, $data): array { $action = Str::upper($action); $namespace = 'finance.adjustment.'.Str::lower($action).'.'.$id; if ($replay = $this->begin($namespace, $data + ['adjustment_id' => $id, 'action' => $action, 'reason' => $reason])) return $replay; $adjustment = $this->find('finance_adjustments', $id, $data, 'Finance adjustment', true); $this->version($adjustment, $data, 'finance adjustment'); $extra = []; $journalId = null;
            if ($action === 'SUBMIT') { $this->status($adjustment, ['DRAFT'], 'Only a draft adjustment can be submitted.'); $to = 'SUBMITTED'; $extra = ['submitted_at' => now(), 'submitted_by' => $data['actor_id']]; }
            elseif ($action === 'APPROVE') { $this->status($adjustment, ['SUBMITTED'], 'Only a submitted adjustment can be approved.'); if ((string) $adjustment->created_by === (string) $data['actor_id']) throw ValidationException::withMessages(['actor' => ['Maker-checker control prevents the adjustment creator from approving it.']]); $to = 'APPROVED'; $extra = ['approved_at' => now(), 'approved_by' => $data['actor_id']]; }
            elseif ($action === 'POST') { $this->status($adjustment, ['APPROVED'], 'Only an approved adjustment can be posted.'); $lines = DB::table('finance_adjustment_lines')->where('finance_adjustment_id', $id)->orderBy('line_number')->get()->map(fn (object $row) => $this->journalLine($row))->all(); $journalId = $this->ledger->postSourceJournal('ADJUSTMENT', 'ADJ-'.$adjustment->adjustment_number, (string) $adjustment->adjustment_date, 'Adjustment '.$adjustment->adjustment_number, 'ADJUSTMENT:'.$id, $lines, $data); $to = 'POSTED'; $extra = ['journal_id' => $journalId, 'posted_at' => now(), 'posted_by' => $data['actor_id']]; }
            elseif ($action === 'CANCEL') { $this->status($adjustment, ['DRAFT', 'SUBMITTED', 'APPROVED'], 'A posted or cancelled adjustment cannot be cancelled.'); if (trim((string) $reason) === '') throw ValidationException::withMessages(['reason' => ['A cancellation reason is required.']]); $to = 'CANCELLED'; $extra = ['cancelled_at' => now(), 'cancelled_by' => $data['actor_id'], 'cancellation_reason' => trim((string) $reason)]; }
            else throw ValidationException::withMessages(['action' => ['Unsupported adjustment action.']]); $version = (int) $adjustment->record_version + 1; DB::table('finance_adjustments')->where('id', $id)->update(['status' => $to, 'record_version' => $version, 'updated_at' => now()] + $extra); $result = $this->result('finance_adjustment', $id, $to, $version, $journalId ? ['journal_id' => $journalId] : []); $this->record($action.'_FINANCE_ADJUSTMENT', 'finance.adjustment.'.Str::lower($action).'d', 'finance_adjustment', $id, $data, $version, ['status' => ['from' => $adjustment->status, 'to' => $to]], $result); $this->complete($namespace, $data, $result); return $result;
        }, 3);
    }

    public function createLegacyImport(array $data): array
    {
        return DB::transaction(function () use ($data): array { $namespace = 'finance.legacy-import.create'; if ($replay = $this->begin($namespace, $data)) return $replay; $this->unique('legacy_import_batches', 'batch_number', $data['batch_number'], $data); $debit = $credit = '0.0000'; $rows = []; foreach ($data['rows'] as $row) { $dr = $this->amount($row['debit_amount'] ?? 0); $cr = $this->amount($row['credit_amount'] ?? 0); if ((bccomp($dr, '0', 4) > 0) === (bccomp($cr, '0', 4) > 0)) throw ValidationException::withMessages(['rows' => ['Each legacy row requires exactly one positive debit or credit amount.']]); $rows[] = ['legacy_account_code' => Str::upper(trim($row['legacy_account_code'])), 'account_id' => $row['account_id'] ?? null, 'description' => trim($row['description']), 'debit_amount' => $dr, 'credit_amount' => $cr, 'source_json' => $row['source'] ?? null]; $debit = bcadd($debit, $dr, 4); $credit = bcadd($credit, $cr, 4); } $id = (string) Str::uuid(); $now = CarbonImmutable::now(); DB::table('legacy_import_batches')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'batch_number' => $data['batch_number'], 'source_system' => trim($data['source_system']), 'posting_date' => $data['posting_date'], 'status' => 'STAGED', 'record_count' => count($rows), 'total_debit' => $debit, 'total_credit' => $credit, 'error_count' => 0, 'validation_json' => null, 'journal_id' => null, 'record_version' => 1, 'created_by' => $data['actor_id'], 'validated_at' => null, 'validated_by' => null, 'posted_at' => null, 'posted_by' => null, 'created_at' => $now, 'updated_at' => $now]); foreach ($rows as $index => $row) DB::table('legacy_import_rows')->insert(['id' => (string) Str::uuid(), 'legacy_import_batch_id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'row_number' => $index + 1, 'legacy_account_code' => $row['legacy_account_code'], 'account_id' => $row['account_id'], 'description' => $row['description'], 'debit_amount' => $row['debit_amount'], 'credit_amount' => $row['credit_amount'], 'validation_status' => 'PENDING', 'validation_message' => null, 'source_json' => isset($row['source_json']) ? json_encode($row['source_json'], JSON_THROW_ON_ERROR) : null, 'created_at' => $now, 'updated_at' => $now]); $result = $this->result('legacy_import_batch', $id, 'STAGED', 1, ['record_count' => count($rows), 'total_debit' => $debit, 'total_credit' => $credit]); $this->record('CREATE_LEGACY_IMPORT', 'finance.legacy-import.staged', 'legacy_import_batch', $id, $data, 1, ['record_count' => count($rows)], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function validateLegacyImport(string $id, array $data): array
    {
        return DB::transaction(function () use ($id, $data): array { $namespace = 'finance.legacy-import.validate.'.$id; if ($replay = $this->begin($namespace, $data + ['batch_id' => $id])) return $replay; $batch = $this->find('legacy_import_batches', $id, $data, 'Legacy import batch', true); $this->version($batch, $data, 'legacy import batch'); $this->status($batch, ['STAGED', 'INVALID'], 'Only a staged or invalid batch can be validated.'); $rows = DB::table('legacy_import_rows')->where('legacy_import_batch_id', $id)->orderBy('row_number')->lockForUpdate()->get(); $errors = [];
            foreach ($rows as $row) { $account = null; if ($row->account_id) $account = DB::table('chart_accounts')->where('id', $row->account_id)->where('company_id', $data['company_id'])->where('status', 'ACTIVE')->first(); if (! $account) $account = DB::table('chart_accounts')->where('company_id', $data['company_id'])->where('account_code', $row->legacy_account_code)->where('status', 'ACTIVE')->first(); $valid = $account !== null; $message = $valid ? null : 'No active chart account matches '.$row->legacy_account_code.'.'; if (! $valid) $errors[] = ['row_number' => (int) $row->row_number, 'message' => $message]; DB::table('legacy_import_rows')->where('id', $row->id)->update(['account_id' => $account?->id, 'validation_status' => $valid ? 'VALID' : 'INVALID', 'validation_message' => $message, 'updated_at' => now()]); }
            if (bccomp($this->decimal($batch->total_debit), $this->decimal($batch->total_credit), 4) !== 0) $errors[] = ['batch' => 'Debit and credit totals do not balance.']; $to = $errors === [] ? 'VALID' : 'INVALID'; $errorCount = min(count($errors), (int) $batch->record_count); $snapshot = ['valid' => $errors === [], 'errors' => $errors, 'total_debit' => $this->decimal($batch->total_debit), 'total_credit' => $this->decimal($batch->total_credit)]; $version = (int) $batch->record_version + 1; DB::table('legacy_import_batches')->where('id', $id)->update(['status' => $to, 'error_count' => $errorCount, 'validation_json' => json_encode($snapshot, JSON_THROW_ON_ERROR), 'validated_at' => now(), 'validated_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $result = $this->result('legacy_import_batch', $id, $to, $version, ['error_count' => $errorCount, 'validation' => $snapshot]); $this->record('VALIDATE_LEGACY_IMPORT', 'finance.legacy-import.validated', 'legacy_import_batch', $id, $data, $version, ['error_count' => $errorCount], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function postLegacyImport(string $id, array $data): array
    {
        return DB::transaction(function () use ($id, $data): array { $namespace = 'finance.legacy-import.post.'.$id; if ($replay = $this->begin($namespace, $data + ['batch_id' => $id])) return $replay; $batch = $this->find('legacy_import_batches', $id, $data, 'Legacy import batch', true); $this->version($batch, $data, 'legacy import batch'); $this->status($batch, ['VALID'], 'Only a valid legacy import can be posted.'); $rows = DB::table('legacy_import_rows')->where('legacy_import_batch_id', $id)->where('validation_status', 'VALID')->orderBy('row_number')->get()->map(fn (object $row) => $this->journalLine($row))->all(); $journalId = $this->ledger->postSourceJournal('LEGACY_IMPORT', 'LEG-'.$batch->batch_number, (string) $batch->posting_date, 'Legacy import '.$batch->batch_number, 'LEGACY_IMPORT:'.$id, $rows, $data); $version = (int) $batch->record_version + 1; DB::table('legacy_import_batches')->where('id', $id)->update(['status' => 'POSTED', 'journal_id' => $journalId, 'posted_at' => now(), 'posted_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $result = $this->result('legacy_import_batch', $id, 'POSTED', $version, ['journal_id' => $journalId]); $this->record('POST_LEGACY_IMPORT', 'finance.legacy-import.posted', 'legacy_import_batch', $id, $data, $version, ['journal_id' => $journalId], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function archive(UploadedFile $file, array $data): array
    {
        $contents = file_get_contents($file->getRealPath());
        if ($contents === false || $contents === '') throw ValidationException::withMessages(['file' => ['The uploaded document is empty or unreadable.']]);
        $checksum = hash('sha256', $contents);
        $extension = strtolower($file->guessExtension() ?: $file->getClientOriginalExtension() ?: 'bin');
        $path = $data['company_id'].'/'.$data['plant_id'].'/'.substr($data['document_date'], 0, 4).'/'.Str::uuid().'.'.$extension;
        $disk = (string) config('qtfoods.private_document_disk', 'private');
        $stored = false;
        try {
            return DB::transaction(function () use ($file, $data, $checksum, $contents, $path, $disk, &$stored): array {
                $namespace = 'finance.archive.upload';
                if ($replay = $this->begin($namespace, $data + ['checksum' => $checksum, 'original_name' => $file->getClientOriginalName()])) return $replay;
                if (DB::table('bill_archive_documents')->where('company_id', $data['company_id'])->where('sha256_checksum', $checksum)->exists()) throw ValidationException::withMessages(['file' => ['This document is already archived.']]);
                $this->unique('bill_archive_documents', 'document_number', $data['document_number'], ['company_id' => $data['company_id']]);
                if ($data['retain_until'] < $data['document_date']) throw ValidationException::withMessages(['retain_until' => ['Retention date cannot precede the document date.']]);
                if (! empty($data['invoice_id']) && ! DB::table('invoices')->where('id', $data['invoice_id'])->where($this->scope($data))->exists()) throw ValidationException::withMessages(['invoice_id' => ['Invoice not found in the selected plant.']]);
                Storage::disk($disk)->put($path, $contents); $stored = true;
                $id = (string) Str::uuid();
                DB::table('bill_archive_documents')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'document_number' => $data['document_number'], 'invoice_id' => $data['invoice_id'] ?? null, 'document_type' => $data['document_type'], 'original_name' => $file->getClientOriginalName(), 'storage_disk' => 'private', 'storage_path' => $path, 'mime_type' => $file->getMimeType() ?: 'application/octet-stream', 'size_bytes' => $file->getSize(), 'sha256_checksum' => $checksum, 'document_date' => $data['document_date'], 'retain_until' => $data['retain_until'], 'notes' => $this->nullable($data['notes'] ?? null), 'record_version' => 1, 'uploaded_by' => $data['actor_id'], 'created_at' => now(), 'updated_at' => now()]);
                $result = $this->result('bill_archive_document', $id, 'ARCHIVED', 1, ['sha256_checksum' => $checksum, 'size_bytes' => $file->getSize()]);
                $this->record('UPLOAD_BILL_ARCHIVE', 'finance.archive.uploaded', 'bill_archive_document', $id, $data, 1, ['document_type' => $data['document_type'], 'sha256_checksum' => $checksum], $result); $this->complete($namespace, $data, $result); return $result;
            }, 3);
        } catch (\Throwable $exception) {
            if ($stored) Storage::disk($disk)->delete($path);
            throw $exception;
        }
    }

    public function createOpeningBalance(array $data): array
    {
        return DB::transaction(function () use ($data): array { $namespace = 'finance.opening-balance.create'; if ($replay = $this->begin($namespace, $data)) return $replay; $this->unique('opening_balance_batches', 'batch_number', $data['batch_number'], $data); [$lines, $debit, $credit] = $this->lines($data['lines'], $data, false); $difference = bcsub($debit, $credit, 4); $id = (string) Str::uuid(); $now = CarbonImmutable::now(); DB::table('opening_balance_batches')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'batch_number' => $data['batch_number'], 'opening_date' => $data['opening_date'], 'status' => 'DRAFT', 'total_debit' => $debit, 'total_credit' => $credit, 'difference_amount' => $difference, 'notes' => $this->nullable($data['notes'] ?? null), 'journal_id' => null, 'record_version' => 1, 'created_by' => $data['actor_id'], 'reconciled_at' => null, 'reconciled_by' => null, 'posted_at' => null, 'posted_by' => null, 'created_at' => $now, 'updated_at' => $now]); foreach ($lines as $index => $line) DB::table('opening_balance_lines')->insert(['id' => (string) Str::uuid(), 'opening_balance_batch_id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'line_number' => $index + 1, 'account_id' => $line['account_id'], 'party_id' => $line['party_id'], 'description' => $line['description'], 'debit_amount' => $line['debit_amount'], 'credit_amount' => $line['credit_amount'], 'source_amount' => bcadd($line['debit_amount'], $line['credit_amount'], 4), 'reconciled_amount' => 0, 'created_at' => $now, 'updated_at' => $now]); $result = $this->result('opening_balance_batch', $id, 'DRAFT', 1, ['total_debit' => $debit, 'total_credit' => $credit, 'difference_amount' => $difference]); $this->record('CREATE_OPENING_BALANCE', 'finance.opening-balance.created', 'opening_balance_batch', $id, $data, 1, ['line_count' => count($lines), 'difference_amount' => $difference], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function reconcileOpeningBalance(string $id, array $reconciliations, array $data): array
    {
        return DB::transaction(function () use ($id, $reconciliations, $data): array { $namespace = 'finance.opening-balance.reconcile.'.$id; if ($replay = $this->begin($namespace, $data + ['batch_id' => $id, 'reconciliations' => $reconciliations])) return $replay; $batch = $this->find('opening_balance_batches', $id, $data, 'Opening balance batch', true); $this->version($batch, $data, 'opening balance batch'); $this->status($batch, ['DRAFT'], 'Only a draft opening balance can be reconciled.'); if (bccomp($this->decimal($batch->difference_amount), '0', 4) !== 0) throw ValidationException::withMessages(['difference_amount' => ['Opening balances must balance before reconciliation.']]); $lines = DB::table('opening_balance_lines')->where('opening_balance_batch_id', $id)->lockForUpdate()->get()->keyBy('id'); if (count($reconciliations) !== $lines->count()) throw ValidationException::withMessages(['lines' => ['Every opening-balance line must be reconciled.']]); foreach ($reconciliations as $input) { $line = $lines->get($input['line_id']); if (! $line) throw ValidationException::withMessages(['lines' => ['A reconciliation line does not belong to this batch.']]); $amount = $this->amount($input['reconciled_amount']); if (bccomp($amount, $this->decimal($line->source_amount), 4) !== 0) throw ValidationException::withMessages(['lines' => ['Reconciled amounts must equal their source amounts.']]); DB::table('opening_balance_lines')->where('id', $line->id)->update(['reconciled_amount' => $amount, 'updated_at' => now()]); } $version = (int) $batch->record_version + 1; DB::table('opening_balance_batches')->where('id', $id)->update(['status' => 'RECONCILED', 'reconciled_at' => now(), 'reconciled_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $result = $this->result('opening_balance_batch', $id, 'RECONCILED', $version); $this->record('RECONCILE_OPENING_BALANCE', 'finance.opening-balance.reconciled', 'opening_balance_batch', $id, $data, $version, ['line_count' => count($reconciliations)], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function postOpeningBalance(string $id, array $data): array
    {
        return DB::transaction(function () use ($id, $data): array { $namespace = 'finance.opening-balance.post.'.$id; if ($replay = $this->begin($namespace, $data + ['batch_id' => $id])) return $replay; $batch = $this->find('opening_balance_batches', $id, $data, 'Opening balance batch', true); $this->version($batch, $data, 'opening balance batch'); $this->status($batch, ['RECONCILED'], 'Only a reconciled opening balance can be posted.'); $lines = DB::table('opening_balance_lines')->where('opening_balance_batch_id', $id)->orderBy('line_number')->get()->map(fn (object $row) => $this->journalLine($row))->all(); $journalId = $this->ledger->postSourceJournal('OPENING_BALANCE', 'OB-'.$batch->batch_number, (string) $batch->opening_date, 'Opening balances '.$batch->batch_number, 'OPENING_BALANCE:'.$id, $lines, $data); $version = (int) $batch->record_version + 1; DB::table('opening_balance_batches')->where('id', $id)->update(['status' => 'POSTED', 'journal_id' => $journalId, 'posted_at' => now(), 'posted_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $result = $this->result('opening_balance_batch', $id, 'POSTED', $version, ['journal_id' => $journalId]); $this->record('POST_OPENING_BALANCE', 'finance.opening-balance.posted', 'opening_balance_batch', $id, $data, $version, ['journal_id' => $journalId], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function createSupportCase(array $data): array
    {
        return DB::transaction(function () use ($data): array { $namespace = 'finance.support.create'; if ($replay = $this->begin($namespace, $data)) return $replay; $this->unique('finance_support_cases', 'case_number', $data['case_number'], $data); $id = (string) Str::uuid(); $now = CarbonImmutable::now(); DB::table('finance_support_cases')->insert(['id' => $id, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'case_number' => $data['case_number'], 'category' => $data['category'], 'severity' => $data['severity'], 'subject' => trim($data['subject']), 'description' => trim($data['description']), 'status' => 'OPEN', 'diagnostic_snapshot' => null, 'resolution_notes' => null, 'record_version' => 1, 'created_by' => $data['actor_id'], 'closed_at' => null, 'closed_by' => null, 'created_at' => $now, 'updated_at' => $now]); $this->supportAction($id, 'NOTE', 'Case opened.', null, $data); $result = $this->result('finance_support_case', $id, 'OPEN', 1); $this->record('CREATE_FINANCE_SUPPORT_CASE', 'finance.support.created', 'finance_support_case', $id, $data, 1, ['severity' => $data['severity']], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function diagnoseSupportCase(string $id, string $notes, array $data): array
    {
        return DB::transaction(function () use ($id, $notes, $data): array { $namespace = 'finance.support.diagnose.'.$id; if ($replay = $this->begin($namespace, $data + ['case_id' => $id, 'notes' => $notes])) return $replay; $case = $this->find('finance_support_cases', $id, $data, 'Finance support case', true); $this->version($case, $data, 'finance support case'); $this->status($case, ['OPEN', 'DIAGNOSED'], 'A closed support case cannot be diagnosed.'); $snapshot = ['captured_at' => now()->toIso8601String(), 'draft_journals' => DB::table('journals')->where($this->scope($data))->where('status', 'DRAFT')->count(), 'unbalanced_openings' => DB::table('opening_balance_batches')->where($this->scope($data))->where('difference_amount', '<>', 0)->count(), 'invalid_imports' => DB::table('legacy_import_batches')->where($this->scope($data))->where('status', 'INVALID')->count(), 'unacknowledged_exports' => DB::table('finance_exports')->where($this->scope($data))->where('status', 'GENERATED')->count()]; $version = (int) $case->record_version + 1; DB::table('finance_support_cases')->where('id', $id)->update(['status' => 'DIAGNOSED', 'diagnostic_snapshot' => json_encode($snapshot, JSON_THROW_ON_ERROR), 'record_version' => $version, 'updated_at' => now()]); $this->supportAction($id, 'DIAGNOSTIC', trim($notes), $snapshot, $data); $result = $this->result('finance_support_case', $id, 'DIAGNOSED', $version, ['diagnostic_snapshot' => $snapshot]); $this->record('DIAGNOSE_FINANCE_SUPPORT_CASE', 'finance.support.diagnosed', 'finance_support_case', $id, $data, $version, $snapshot, $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    public function closeSupportCase(string $id, string $resolution, array $data): array
    {
        return DB::transaction(function () use ($id, $resolution, $data): array { $namespace = 'finance.support.close.'.$id; if ($replay = $this->begin($namespace, $data + ['case_id' => $id, 'resolution' => $resolution])) return $replay; $case = $this->find('finance_support_cases', $id, $data, 'Finance support case', true); $this->version($case, $data, 'finance support case'); $this->status($case, ['OPEN', 'DIAGNOSED'], 'The support case is already closed.'); $version = (int) $case->record_version + 1; DB::table('finance_support_cases')->where('id', $id)->update(['status' => 'CLOSED', 'resolution_notes' => trim($resolution), 'closed_at' => now(), 'closed_by' => $data['actor_id'], 'record_version' => $version, 'updated_at' => now()]); $this->supportAction($id, 'CLOSE', trim($resolution), null, $data); $result = $this->result('finance_support_case', $id, 'CLOSED', $version); $this->record('CLOSE_FINANCE_SUPPORT_CASE', 'finance.support.closed', 'finance_support_case', $id, $data, $version, ['resolution' => $resolution], $result); $this->complete($namespace, $data, $result); return $result; }, 3);
    }

    private function lines(array $lines, array $data, bool $balanced): array
    {
        $prepared = []; $debit = $credit = '0.0000'; foreach ($lines as $line) { $this->account($line['account_id'], $data); if (! empty($line['party_id']) && ! DB::table('parties')->where('id', $line['party_id'])->where('company_id', $data['company_id'])->exists()) throw ValidationException::withMessages(['party_id' => ['Party not found in the selected company.']]); $dr = $this->amount($line['debit_amount'] ?? 0); $cr = $this->amount($line['credit_amount'] ?? 0); if ((bccomp($dr, '0', 4) > 0) === (bccomp($cr, '0', 4) > 0)) throw ValidationException::withMessages(['lines' => ['Each line requires exactly one positive debit or credit amount.']]); $prepared[] = ['account_id' => $line['account_id'], 'party_id' => $line['party_id'] ?? null, 'description' => trim($line['description']), 'debit_amount' => $dr, 'credit_amount' => $cr, 'assumption' => $this->nullable($line['assumption'] ?? null)]; $debit = bcadd($debit, $dr, 4); $credit = bcadd($credit, $cr, 4); } if (count($prepared) < 2) throw ValidationException::withMessages(['lines' => ['At least two lines are required.']]); if ($balanced && bccomp($debit, $credit, 4) !== 0) throw ValidationException::withMessages(['lines' => ['Debit and credit totals must balance.']]); return [$prepared, $debit, $credit];
    }

    private function insertLines(string $table, string $foreignKey, string $parentId, array $lines, array $data, CarbonImmutable $now, bool $simulation = false): void { foreach ($lines as $index => $line) { $row = ['id' => (string) Str::uuid(), $foreignKey => $parentId, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'line_number' => $index + 1, 'account_id' => $line['account_id'], 'description' => $line['description'], 'debit_amount' => $line['debit_amount'], 'credit_amount' => $line['credit_amount'], 'created_at' => $now, 'updated_at' => $now]; if ($simulation) $row['assumption'] = $line['assumption']; else $row['party_id'] = $line['party_id']; DB::table($table)->insert($row); } }
    private function supportAction(string $caseId, string $type, string $notes, ?array $diagnostic, array $data): void { DB::table('finance_support_actions')->insert(['id' => (string) Str::uuid(), 'finance_support_case_id' => $caseId, 'company_id' => $data['company_id'], 'plant_id' => $data['plant_id'], 'action_type' => $type, 'notes' => $notes, 'diagnostic_json' => $diagnostic ? json_encode($diagnostic, JSON_THROW_ON_ERROR) : null, 'actor_id' => $data['actor_id'], 'created_at' => now()]); }
    private function journalLine(object $row): array { return ['account_id' => $row->account_id, 'party_id' => $row->party_id ?? null, 'description' => $row->description, 'debit_amount' => $this->decimal($row->debit_amount, 4), 'credit_amount' => $this->decimal($row->credit_amount, 4)]; }
    private function account(string $id, array $data): object { $account = DB::table('chart_accounts')->where('id', $id)->where('company_id', $data['company_id'])->where('status', 'ACTIVE')->first(); if (! $account) throw ValidationException::withMessages(['account_id' => ['Active chart account not found.']]); return $account; }
    private function find(string $table, string $id, array $data, string $label, bool $lock = false): object { $query = DB::table($table)->where('id', $id)->where($this->scope($data)); $record = ($lock ? $query->lockForUpdate() : $query)->first(); if (! $record) throw new NotFoundHttpException($label.' not found.'); return $record; }
    private function unique(string $table, string $column, string $value, array $data): void { $query = DB::table($table)->where('company_id', $data['company_id'])->where($column, $value); if (! empty($data['plant_id'])) $query->where('plant_id', $data['plant_id']); if ($query->exists()) throw ValidationException::withMessages([$column => ['That identifier already exists in the selected scope.']]); }
    private function scope(array $data): array { return ['company_id' => $data['company_id'], 'plant_id' => $data['plant_id']]; }
    private function version(object $record, array $data, string $label): void { if ((int) $record->record_version !== (int) $data['expected_version']) throw new ConflictHttpException("The {$label} changed. Refresh it before continuing."); }
    private function status(object $record, array $allowed, string $message): void { if (! in_array($record->status, $allowed, true)) throw ValidationException::withMessages(['status' => [$message]]); }
    private function amount(mixed $value): string { $text = (string) ($value ?? 0); if (! preg_match('/^\d{1,14}(?:\.\d{1,4})?$/', $text)) throw ValidationException::withMessages(['amount' => ['Amounts must be non-negative with at most four decimal places.']]); return bcadd($text, '0', 4); }
    private function decimal(mixed $value, int $scale = 4): string { return bcadd((string) ($value ?? 0), '0', $scale); }
    private function nullable(mixed $value): ?string { $value = trim((string) ($value ?? '')); return $value === '' ? null : $value; }
    private function result(string $entity, string $id, string $status, int $version, array $extra = []): array { return ['entity_type' => $entity, 'id' => $id, 'status' => $status, 'record_version' => $version] + $extra; }
    private function begin(string $namespace, array $data): ?array { return $this->idempotency->begin($namespace, $data['idempotency_key'], Arr::except($data, ['actor_id', 'permissions', 'idempotency_key', 'correlation_id', 'file'])); }
    private function complete(string $namespace, array $data, array $result): void { $this->idempotency->complete($namespace, $data['idempotency_key'], $result); }
    private function record(string $command, string $event, string $entity, string $id, array $data, int $version, array $diff, array $result): void { $this->audit->record($command, $entity, $id, $data['actor_id'], $data['company_id'], $data['plant_id'], 'SUCCESS', ['entity_version' => $version, 'correlation_id' => $data['correlation_id'] ?? null, 'safe_diff' => $diff]); $this->outbox->append($event, $entity, $id, $id.':'.$version, $result + ['company_id' => $data['company_id'], 'plant_id' => $data['plant_id']], $data['correlation_id'] ?? null, $data['company_id'], $data['plant_id']); }
}
